'use client'

import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Zap, GitPullRequest, ShieldCheck, Terminal, Loader2, Database, AlertCircle, ExternalLink } from 'lucide-react'
import useSWR, { useSWRConfig } from 'swr'
import { PatchDiffViewer } from '@/components/patch-diff-viewer'
import { LogViewer } from '@/components/log-viewer'
import { useState } from 'react'
import { formatDistanceToNow } from 'date-fns'
import { cn } from '@/lib/utils'

const fetcher = (url: string) => fetch(url).then((res) => res.json())

export default function AIRecommendationsPage() {
  const { mutate } = useSWRConfig()
  const { data: incidents, error, isLoading } = useSWR('/api/incidents', fetcher)
  const [showLogViewer, setShowLogViewer] = useState(false)
  const [logs, setLogs] = useState('')
  const [isCreatingPR, setIsCreatingPR] = useState<string | null>(null)

  const handleCreatePR = async (issue: any) => {
    if (!issue) return
    
    setIsCreatingPR(issue.id)
    try {
      const res = await fetch(`/api/issues/${issue.id}/create-pr`, {
        method: 'POST'
      })
      if (res.ok) {
        await mutate('/api/incidents')
      }
    } catch (err) {
      console.error('Failed to create PR:', err)
    } finally {
      setIsCreatingPR(null)
    }
  }

  const handleViewLogs = async (workflowRunId: string) => {
    try {
      const res = await fetch(`/api/workflow-runs/${workflowRunId}/logs`)
      if (res.ok) {
        const data = await res.json()
        setLogs(data.logs)
        setShowLogViewer(true)
      }
    } catch (err) {
      console.error('Failed to fetch logs:', err)
    }
  }

  // Filter to only incidents that have issues with patches
  const recommendations = incidents?.flatMap((i: any) => 
    (i.issues || []).map((issue: any) => ({
      ...issue,
      incident: i,
      repository: i.repository,
      workflowRun: i.workflowRun
    }))
  ).filter((issue: any) => issue.patches?.length > 0) || []

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      {showLogViewer && <LogViewer logs={logs} onClose={() => setShowLogViewer(false)} />}
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground tracking-tight text-white uppercase italic">AI Fix Engine</h1>
          <p className="text-sm text-muted-foreground mt-1">Ready-to-merge pull requests generated by CORI.</p>
        </div>
      </div>

      {/* Recommendations */}
      <div className="space-y-6">
        {recommendations.length > 0 ? recommendations.map((issue: any) => {
          const patch = issue.patches?.[0]
          
          return (
            <Card key={issue.id} className="overflow-hidden border-border bg-card shadow-sm">
              {/* Header */}
              <div className="p-5 border-b border-border bg-secondary/10 flex items-start justify-between">
                <div className="flex items-start gap-3">
                  <div className="mt-1">
                    <ShieldCheck className="w-5 h-5 text-emerald-500" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-foreground tracking-tight">{issue.title}</h3>
                    <div className="flex items-center gap-4 mt-2">
                      <Badge variant="outline" className="text-[10px] font-mono bg-background">
                        Confidence: <span className="text-blue-500 ml-1 font-bold">{issue.confidence}%</span>
                      </Badge>
                      <span className="text-xs text-muted-foreground flex items-center gap-1 font-mono">
                        <Database className="w-3 h-3" />
                        {issue.repository.fullName}
                      </span>
                      {patch && (
                        <span className="text-[10px] text-muted-foreground font-mono">
                          Generated {formatDistanceToNow(new Date(patch.createdAt))} ago
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2">
                {/* Context Panel */}
                <div className="p-5 border-r border-border bg-card space-y-6">
                  <div>
                    <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold mb-2">Category</p>
                    <p className="text-sm text-foreground">{issue.category}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold mb-2">Root Cause Analysis</p>
                    <p className="text-sm text-foreground leading-relaxed">{issue.rootCause}</p>
                  </div>
                  {patch && (
                    <div className="pt-4 border-t border-border">
                      <p className="text-xs text-muted-foreground uppercase tracking-wider font-semibold mb-3">Patch Metadata</p>
                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-1">
                          <p className="text-[10px] text-muted-foreground uppercase tracking-widest font-bold opacity-50">Status</p>
                          <Badge variant="outline" className={cn(
                            "text-[10px] font-bold",
                            patch.status === 'APPROVED' ? "border-emerald-500/50 text-emerald-500 bg-emerald-500/5" : 
                            patch.status === 'FAILED' ? "border-red-500/50 text-red-500 bg-red-500/5" :
                            patch.status === 'PR_CREATED' ? "border-blue-500/50 text-blue-500 bg-blue-500/5" : 
                            "border-amber-500/50 text-amber-500 bg-amber-500/5"
                          )}>
                            {patch.status}
                          </Badge>
                        </div>
                        <div className="space-y-1">
                          <p className="text-[10px] text-muted-foreground uppercase tracking-widest font-bold opacity-50">Affected File</p>
                          <p className="text-xs font-mono text-foreground">{issue.file}</p>
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                {/* Code Diff Panel */}
                <div className="p-0 bg-background flex flex-col">
                  <div className="p-2 border-b border-border bg-secondary/50 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Terminal className="w-3 h-3 text-muted-foreground" />
                      <span className="text-[10px] font-mono text-muted-foreground">Generated Fix Preview</span>
                    </div>
                  </div>
                  <div className="flex-1 p-4 overflow-x-auto">
                    {patch ? (
                      <PatchDiffViewer diff={patch.diff} fileName={issue.file} />
                    ) : (
                      <div className="h-full flex flex-col items-center justify-center py-12 text-center">
                        <AlertCircle className="w-8 h-8 text-muted-foreground opacity-30 mb-2" />
                        <p className="text-xs text-muted-foreground">No patch generated yet</p>
                      </div>
                    )}
                  </div>
                  
                  {/* Actions */}
                  <div className="p-4 bg-secondary/30 border-t border-border flex flex-wrap items-center justify-end gap-3">
                    <Button variant="ghost" className="text-xs text-muted-foreground hover:text-foreground h-8" onClick={() => handleViewLogs(issue.workflowRun.id)}>
                      View Logs
                    </Button>
                    <Button 
                      className="h-8 text-xs bg-blue-600 hover:bg-blue-700 text-white gap-2" 
                      disabled={!patch || isCreatingPR === issue.id}
                      onClick={() => handleCreatePR(issue)}
                    >
                      {isCreatingPR === issue.id ? (
                        <Loader2 className="w-3 h-3 animate-spin" />
                      ) : (
                        <GitPullRequest className="w-3 h-3" />
                      )}
                      {issue.status === 'PR_CREATED' ? 'View Pull Request' : 'Create Pull Request'}
                    </Button>
                  </div>
                </div>
              </div>
            </Card>
          )
        }) : (
          <div className="text-center py-20 border-2 border-dashed border-border rounded-xl">
            <ShieldCheck className="w-12 h-12 text-muted-foreground mb-4 mx-auto" />
            <h2 className="text-lg font-medium text-foreground text-white">No pending AI fixes</h2>
            <p className="text-sm text-muted-foreground">CORI will generate automated fixes when pipeline failures are analyzed.</p>
          </div>
        )}
      </div>
    </div>
  )
}
